### ISSUE TITLE
Chomp 0.2.12 fails to install on macOS

### ISSUE THREAD

**Issue by connor4312** [guybedford/chomp#162]
1. Install chomp 0.2.12 from npm (latest version)
2. Try to run a chomp command
3. Receive the following error:

```
                        proxy.emit('error', new got.HTTPError(statusCode, res.statusMessage, res.headers, opts), null, res);
                                            ^

GotError [HTTPError]: Response code 404 (Not Found)
    at EventEmitter.<anonymous> (/Users/connor/Github/blockerator/node_modules/download/node_modules/got/index.js:482:24)
    at EventEmitter.emit (node:events:527:28)
    at getResponse (/Users/connor/Github/blockerator/node_modules/download/node_modules/got/index.js:320:5)
    at Immediate.<anonymous> (/Users/connor/Github/blockerator/node_modules/download/node_modules/got/index.js:147:6)
    at processImmediate (node:internal/timers:466:21) {
  host: 'github.com',
  hostname: 'github.com',
  method: 'GET',
  path: '/guybedford/chomp/releases/download/0.2.12/chomp-macos-0.2.12.tar.gz',
  protocol: 'https:',
  url: 'https://github.com/guybedford/chomp/releases/download/0.2.12/chomp-macos-0.2.12.tar.gz',
  statusCode: 404,
  statusMessage: 'Not Found',
  headers: {
    server: 'GitHub.com',
    date: 'Sun, 12 Feb 2023 01:22:25 GMT',
    'content-type': 'text/plain; charset=utf-8',
    vary: 'X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With',
    'cache-control': 'no-cache',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'x-frame-options': 'deny',
    'x-content-type-options': 'nosniff',
    'x-xss-protection': '0',
    'referrer-policy': 'no-referrer-when-downgrade',
    'content-security-policy': "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
    'content-encoding': 'gzip',
    'content-length': '29',
    'x-github-request-id': 'E12C:4445:27DB23:3048B1:63E83F51',
    connection: 'close'
  }
}
```

**Comment by zachsa** [comment]
This is on Linux as well

**Comment by guybedford** [comment]
Thanks, a CI error caused the automated deployment to fail. I've repushed the tag and fixed the flake. The builds should be uploaded in the next 30 mins.

**Comment by guybedford** [comment]
There was still another release workflow issue - finally fixed..!
