### ISSUE TITLE
main panicked

### ISSUE THREAD

**Issue by canadaduane** [guybedford/chomp#20]
I pulled the latest commit and recompiled, but `chomp svelte` now panics:

```$ RUST_BACKTRACE=1 chomp svelte
- package.json [- 182.396µs]
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/task.rs:1004:58
stack backtrace:
   0: rust_begin_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
   2: core::panicking::panic
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:50:5
   3: core::option::Option<T>::unwrap
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/option.rs:735:21
   4: chomp::task::Runner::drive_completion
             at /home/duane/tmp/chomp/src/task.rs:1004:34
   5: chomp::task::Runner::drive_all
             at /home/duane/tmp/chomp/src/task.rs:887:37
   6: chomp::task::Runner::drive_completion
             at /home/duane/tmp/chomp/src/task.rs:998:17
   7: chomp::task::Runner::drive_targets::{{closure}}
             at /home/duane/tmp/chomp/src/task.rs:1328:13
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/future/mod.rs:80:19
   9: chomp::task::run::{{closure}}
             at /home/duane/tmp/chomp/src/task.rs:1434:5
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/future/mod.rs:80:19
  11: chomp::main::{{closure}}
             at /home/duane/tmp/chomp/src/main.rs:105:14
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/future/mod.rs:80:19
  13: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /home/duane/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/park/thread.rs:263:54
  14: tokio::coop::with_budget::{{closure}}
             at /home/duane/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/coop.rs:106:9
  15: std::thread::local::LocalKey<T>::try_with
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/thread/local.rs:399:16
  16: std::thread::local::LocalKey<T>::with
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/thread/local.rs:375:9
  17: tokio::coop::with_budget
             at /home/duane/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/coop.rs:99:5
  18: tokio::coop::budget
             at /home/duane/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/coop.rs:76:5
  19: tokio::park::thread::CachedParkThread::block_on
             at /home/duane/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/park/thread.rs:263:31
  20: tokio::runtime::enter::Enter::block_on
             at /home/duane/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/enter.rs:151:13
  21: tokio::runtime::thread_pool::ThreadPool::block_on
             at /home/duane/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/thread_pool/mod.rs:77:9
  22: tokio::runtime::Runtime::block_on
             at /home/duane/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/mod.rs:463:43
  23: chomp::main
             at /home/duane/tmp/chomp/src/main.rs:113:5
  24: core::ops::function::FnOnce::call_once
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

chompfile.toml
```
version = 0.1

[[task]]
  name = "svelte"
  template = "chomp:svelte"
  target = "lib/#.js"
  deps = ["src/#.svelte"]
```

Note that the above chompfile and setup seems to work fine prior to https://github.com/guybedford/chomp/commit/465ed945c5fd8122b5d6460832b0437694d2029c

**Comment by guybedford** [comment]
Just fixed this in the latest commit - was also happening on CI.
